name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: flake8 src/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -v

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag quant-llm-assistant:latest

git add .github/workflows/ci.yml
git commit -m "Add CI workflow for linting, testing, and Docker build"
